-- ========== REQUIREMENT-BASED MATCHING SYSTEM MIGRATIONS ==========
-- Run this in Supabase SQL Editor to add client requirements functionality

-- Client Projects with Requirements
CREATE TABLE IF NOT EXISTS client_requirements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_title TEXT NOT NULL,
  project_description TEXT,
  required_skills_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Link required skills to each client requirement
CREATE TABLE IF NOT EXISTS requirement_skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requirement_id BIGINT NOT NULL REFERENCES client_requirements(id) ON DELETE CASCADE,
  skill_name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(requirement_id, skill_name)
);

CREATE INDEX IF NOT EXISTS idx_requirement_skills_req_id ON requirement_skills(requirement_id);

-- ========== END MIGRATIONS ==========
